[theme]

# Primary accent for interactive elements
primaryColor = '#5447de'

# Background color for the main content area
backgroundColor = '#273346'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#040806'

# Color used for almost all text
textColor = '#f2f5f4'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"